export const SET_GESTURE = "SET_GESTURE";
export const ADD_COMBINATION = "ADD_COMBINATION";
export const SET_MODE = "SET_MODE";
export const GESTURE_ACTIVE = "GESTURE_ACTIVE";
export const GESTURE_INACTIVE = "GESTURE_INACTIVE";
export const USER_ACTIVE = "USER_ACTIVE";
export const USER_INACTIVE = "USER_INACTIVE";
export const INCREMENT_COUNT = "INCREMENT_COUNT";
