export const INCREMENT_COUNT = "INCREMENT_COUNT";
export const GESTURE_ACTIVE = "GESTURE_ACTIVE";
export const GESTURE_INACTIVE = "GESTURE_INACTIVE";
export const USER_ACTIVE = "USER_ACTIVE";
export const USER_INACTIVE = "USER_INACTIVE";
