export const INCREMENT_COUNT = "INCREMENT COUNT";
export const ADD_TO_EXPIRED = "ADD POSITION TO EXPIRED QUEUE";
export const SAVE_NEW_POSITION = "SAVE NEW POSITION";
export const GESTURE_IN_PROGRESS = "GESTURE_IN_PROGRESS";
export const GESTURE_NOT_IN_PROGRESS = "GESTURE_NOT_IN_PROGRESS";
export const UPDATE_INPUT_TIME = "UPDATE_INPUT_TIME";
